# Generated by Django 3.1.3 on 2020-11-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=1024)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
