# Generated by Django 3.1.3 on 2020-11-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_achievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
