# Generated by Django 3.1.4 on 2020-12-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
