# Generated by Django 3.1.4 on 2020-12-03 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='points',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentreward',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
