# Generated by Django 3.1.4 on 2020-12-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201203_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='points',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
